name: Update-Thoitiet

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  update-thoitiet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
      - name: Set up environment
        run: |
            echo "APIKEY=${{ secrets.APIKEY }}" >> $GITHUB_ENV
      - name : update thoitiet
        env:
          APIKEY: ${{ secrets.APIKEY }}
        shell: bash
        run : |
          bash auto.sh
      - name: push updated thoitiet
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: update-thoitiet
      - name: Cleanup artifacts
        uses: dev-drprasad/delete-older-artifacts@v1
        with:
          days-old: 1
          fail-on-error: false
